HTML_HEAD: "
  <!DOCTYPE html>
  <html>
    <head>
      <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">
      <title>Webserver Log Result</title>
    </head>
    <body>
    <h1>Webserver Log Result</h1>
  <table class=\"table\">
  <thead>
    <tr>
      <th scope=\"col\">#</th>
      <th scope=\"col\">PATH</th>
      <th scope=\"col\">TOTAL VIEW</th>
      <th scope=\"col\">TOTAL VISITOR (UNIQUE)</th>
    </tr>
  </thead>
  <tbody>
"
HTML_FOOTER: "
</tbody>
</table>
  </body>
</html>"
